name: Test Workflow
on: push
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Set up Node.js
          uses: actions/setup-node@v4
        - name: Install dependencies
          run: |
            npm install
            npm ci
        - name: Lint the project
          run: |
            echo "Linting the project..."
            npm lint
        - name: Build the code
          run: |
            echo "Building the code..."
            npm build
        - name: Run tests
          run: |
            echo "Running tests..."
            npm test
        - name: Deploy to production
          run: |
            echo "Deploying to production..."
            echo "Deployment complete!"

      



